"""Clean JIT compilation artifacts of the OptiX tracers so that the next run
triggers a fresh rebuild.

What gets removed per tracer:
  - The torch cpp_extension build directory
    ($TORCH_EXTENSIONS_DIR or ~/.cache/torch_extensions, any python/cuda
    version subfolder), e.g. .../py312_cu118/lib3dgrt_cc
  - threedgrt_tracer only: slang-generated kernel headers
    (threedgrt_tracer/include/3dgrt/kernels/slang/*.cuh*), which are
    regenerated by slangc at build time.

By default all three tracers are cleaned. Use --ignore to keep specific ones:

    # Clean everything
    python scripts/clean_jit.py

    # Clean only water_tracer (keep the 3dgrt/3dgut builds)
    python scripts/clean_jit.py --ignore threedgrt_tracer --ignore threedgut_tracer

    # Preview without deleting
    python scripts/clean_jit.py --dry-run
"""

import argparse
import glob
import os
import shutil

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# tracer name -> torch cpp_extension module name (see each setup_*.py)
TRACERS = {
    "threedgrt_tracer": "lib3dgrt_cc",
    "threedgut_tracer": "lib3dgut_cc",
    "water_tracer": "libwtracer_cc",
}

# Generated files inside the repo tree (per tracer), relative to REPO_ROOT.
IN_TREE_ARTIFACTS = {
    "threedgrt_tracer": ["threedgrt_tracer/include/3dgrt/kernels/slang/*.cuh*"],
    "threedgut_tracer": [],
    "water_tracer": [],
}


def extensions_root():
    """Mirror torch.utils.cpp_extension's default build root."""
    if os.environ.get("TORCH_EXTENSIONS_DIR"):
        return os.environ["TORCH_EXTENSIONS_DIR"]
    return os.path.join(os.path.expanduser("~"), ".cache", "torch_extensions")


def collect_targets(tracer):
    """All filesystem paths that should be removed for a tracer."""
    targets = []
    # torch extension build dirs across all python/cuda version subfolders
    pattern = os.path.join(extensions_root(), "*", TRACERS[tracer])
    targets.extend(d for d in glob.glob(pattern) if os.path.isdir(d))
    # in-tree generated files
    for pat in IN_TREE_ARTIFACTS[tracer]:
        targets.extend(glob.glob(os.path.join(REPO_ROOT, pat)))
    return sorted(set(targets))


def main():
    parser = argparse.ArgumentParser(
        description="Clean JIT build artifacts of the OptiX tracers (default: clean all)."
    )
    parser.add_argument(
        "--ignore",
        action="append",
        default=[],
        choices=sorted(TRACERS.keys()),
        help="Tracer to keep (repeatable). By default all tracers are cleaned.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print what would be removed, without deleting.",
    )
    args = parser.parse_args()

    to_clean = [t for t in TRACERS if t not in args.ignore]
    if not to_clean:
        print("Nothing to clean (all tracers ignored).")
        return

    n_removed = 0
    for tracer in to_clean:
        targets = collect_targets(tracer)
        print(f"[{tracer}]")
        if not targets:
            print("  (no artifacts found)")
            continue
        for path in targets:
            print(f"  {'would remove' if args.dry_run else 'remove'}: {path}")
            if not args.dry_run:
                if os.path.isdir(path):
                    shutil.rmtree(path)
                else:
                    os.remove(path)
                n_removed += 1
    for tracer in args.ignore:
        print(f"[{tracer}] kept (ignored)")

    if args.dry_run:
        print("Dry run, nothing was deleted.")
    else:
        print(f"Done, removed {n_removed} item(s). Next run will recompile from scratch.")


if __name__ == "__main__":
    main()
